spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    flyway:
        enabled: true
        validate-on-migrate: true
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:sqlite:src/main/resources/db/database.sqlite
        driver-class-name: org.sqlite.JDBC

server:
    port: 8044
